일기 조회 API 버그 수정 및 구현 완료
MaumDiaryApp/maum_backend pull request #9
Opened 2024-05-15 08:47 UTC by haeongg

### PR 타입(하나 이상의 PR 타입을 선택해주세요)
-[✔] 기능 추가
-[] 기능 삭제
-[✔] 버그 수정
-[] 의존성, 환경 변수, 빌드 관련 코드 업데이트

### 반영 브랜치
fix/get-diary -> main

### 변경 사항

- 전체 일기 조회 시, 서버에서 500 에러가 발생하는 문제를 해결했습니다. 
   -> DiaryDto에 빌더 패턴을 사용하여 코드 리팩토링하고, 의존성을 한방향으로 하기 위해 entitiy -> dto로 변환하는 
        to() 를 구현했습니다. 
- 일기를 1개만 조회하는 기능을 추가했습니다. 

### 테스트 결과
**### 일기  작성하기 API**
1. post 2번하여 일기를 2개 생성합니다.  
   parameter에 user_id 값을 넣고, request body에 date, content, image, location 값을 넣어서 api 요청을 보 
   냅니다.
![image](https://github.com/MaumDiaryApp/maum_backend/assets/157338828/eee4553b-05ad-4792-99b7-5aa6d58d69bc)
![image](https://github.com/MaumDiaryApp/maum_backend/assets/157338828/75008601-f534-4c92-b016-7324101820d2)

2. h2-console에서 diary 테이블에 데이터가 추가되었는지 확인합니다. 
![image](https://github.com/MaumDiaryApp/maum_backend/assets/157338828/6e21a4cd-620f-4233-8621-fce7a1633763)

**### 일기 전체 조회하기 API**
1. request parameter에 user_id =1을 입력하고 api를 호출합니다.
![image](https://github.com/MaumDiaryApp/maum_backend/assets/157338828/6bc4af51-7ae3-4b6c-85e3-e8a4d8b3ac44)

2. user_id = 1에 작성된 전체 2개의 일기들이 올바르게 reponse body에 담겨온 것을 확인합니다. 
![image](https://github.com/MaumDiaryApp/maum_backend/assets/157338828/b36780ce-a9eb-4226-8dfd-246aba12510d)

**### 일기 단일 조회하기 API**
1. request parameter에 user_id =1, diary_id=1(조회하고자 하는 일기의 id) 을 입력하고 api를 호출합니다.
![image](https://github.com/MaumDiaryApp/maum_backend/assets/157338828/9ff41d40-1fe3-4f33-ac92-f99012bd337f)

2. 1번째 일기가 조회됩니다. 
![image](https://github.com/MaumDiaryApp/maum_backend/assets/157338828/542100ac-8a6e-4dbe-8200-a307d65afee9)

3.  user_id =1, diary_id=2 을 입력하여 api 호출하고, 2번째 일기가 조회됩니다.   
![image](https://github.com/MaumDiaryApp/maum_backend/assets/157338828/80053c20-c1f2-44c1-99df-f37bd0066385)
![image](https://github.com/MaumDiaryApp/maum_backend/assets/157338828/5d4ed743-cca8-4dfe-ab16-33f7eff057b8)

2024-05-16 02:39 UTC, Leehyeonju0219 requested changes
DB의 테이블 형식에서 date를 localdate(혹은 LocalDateTime)로 변경해주세요.
그리고 클라이언트에서 API 요청을 받을 때, date를 String('yyyy-MM-dd')으로 받아주세요.

2024-05-16 02:39 UTC, Leehyeonju0219 commented on src/main/java/com/example/maum_backend/service/DiaryService.java
> +        DiaryDTO diaryDTO = new DiaryDTO(createdAt, userId, request.getDate(), request.getContent(), request.getImage(), request.getLocation());        Diary diary = diaryRepository.save(diaryDTO.to(
- date를 '5월 1일' 이런 식으로 저장하는 것은 데이터를 관리하는 데에 좋지 않은 듯합니다.
- 프론트에서 요청을 받을 때 date='yyyy-MM-dd'로 입력을 받아야 할 것 같습니다.(연도가 빠지면 1년이 지날 때마다 date가 겹치게 됨.)
- 프론트에서 String으로 입력을 받아서('yyyy-MM-dd') DB에 localdate 형식으로 넣어주세요. (DB에도 String 형식으로 넣게 되면 쿼리 사용 시, date 비교문을 사용할 수 없음)

2024-05-17 12:49 UTC, Leehyeonju0219 commented
Diary 테이블 및 코드 수정 필요
#10

2024-05-17 12:49 UTC, closed without merging

2024-05-24 07:59 UTC, haeongg commented on src/main/java/com/example/maum_backend/service/DiaryService.java
> +        DiaryDTO diaryDTO = new DiaryDTO(createdAt, userId, request.getDate(), request.getContent(), request.getImage(), request.getLocation());        Diary diary = diaryRepository.save(diaryDTO.to(
수정사항 확인후 코드 변경했습니다